apiVersion: v1
kind: Service
metadata:
  name: bots
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.bots.service.port }}
    targetPort: {{ .Values.bots.service.targetPort }}
  selector:
    app: bots
