apiVersion: v1
kind: Service
metadata:
  name: listener
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.listener.service.port }}
    targetPort: {{ .Values.listener.service.targetPort }}
  selector:
    app: listener
