apiVersion: v1
kind: Service
metadata:
  name: nats-streaming
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.nats.service.port }}
    targetPort: {{ .Values.nats.service.targetPort }}
  selector:
    app: nats-streaming
